version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test1_db
    ports:
      - "5432:5432"


  service1:
    build:
      context: ./service1
    env_file:
      - ./service1/.env
    environment:
      DB_HOST: db
      HISTORY_SERVICE_URL: http://service2:3001
    ports:
      - "3000:3000"
    depends_on:
      - db


  service2:
    build:
      context: ./service2
    env_file:
      - ./service2/.env
    environment:
      DB_HOST: db
    ports:
      - "3001:3001"
    depends_on:
      - db
